services:
  craweb-db:
    platform: linux/amd64
    image: library/mysql:9.1.0
    container_name: craweb_db

    environment:
      MYSQL_USER: craweb
      MYSQL_DATABASE: cra_web
      MYSQL_PASSWORD: dnwnchlrkd206
      MYSQL_ROOT_PASSWORD: dnwnchlrkd206
    volumes:
      - "/home/chan/life-log/database/:/var/lib/mysql"
    ports:
      - "3306:3306"

  craweb:
    image: lkyoung/craweb
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: craweb-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://lifelog_db:3306/cra_web
      SPRING_DATASOURCE_USERNAME: craweb
      SPRING_DATASOURCE_PASSWORD: dnwnchlrkd206
