services:
  craweb:
    image: lkyoung/craweb
    platform: linux/amd64
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://lifelog_db:3306/cra_web
      SPRING_DATASOURCE_USERNAME: craweb
      SPRING_DATASOURCE_PASSWORD: dnwnchlrkd206
