services:
  craweb:
    image: lkyoung/craweb
    container_name: craweb
    platform: linux/amd64
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - craweb-network
    volumes:
      - ./logs:/app/log

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - craweb-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - craweb-network
    volumes:
      - grafana_data:/var/lib/grafana  # Grafana 데이터 영속화
      - ./grafana/provisioning:/etc/grafana/provisioning  # 설정 파일 유지

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki.yml:/etc/loki/loki.yml
    command:
      - '--config.file=/etc/loki/loki.yml'
    ports:
      - "3100:3100"
    networks:
      - craweb-network

networks:
  craweb-network:
    driver: bridge