services:
  craweb:
    image: lkyoung/craweb
    platform: linux/amd64
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://lkyoungdbinstanse.cpes68q0s4xy.ap-northeast-2.rds.amazonaws.com:3306/craweb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dnwnchlrkd206
