spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: ${REDIS_TIMEOUT}


  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
        endpoint: ${AWS_S3_ENDPOINT}
        public-url: ${AWS_S3_PUBLIC_URL}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXP}
  refresh-expiration: ${JWT_REFRESH_EXP}

aes:
  algorithm: ${AES_ALGO}
  security-key: ${AES_KEY}
  iv: ${AES_IV}

logging:
  level:
    root: info
    org.springframework.web: info
    com.handong.cra.crawebbackend: info
  file:
    name: ${LOG_FILE}

dev-site:
  test-server:
    url: ${DEV-SITE_TEST-SERVER_URL}


